#ifndef LIBTUXCLOCKER_H_
#define LIBTUXCLOCKER_H_

// Enums for types of sensor reading
enum sensor_type {SENSOR_TEMP, SENSOR_FAN_PERCENTAGE, SENSOR_FAN_RPM, SENSOR_CORE_CLOCK, SENSOR_CORE_VOLTAGE, 
	SENSOR_POWER_DRAW, SENSOR_CORE_UTILIZATION, SENSOR_MEMORY_CLOCK, SENSOR_MEMORY_UTILIZATION,
	SENSOR_MEMORY_MB_USAGE};

extern char *sensor_names[16];

enum gpu_type {AMD, NVIDIA};

#endif
